/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as math from "./math";
export type { math };
import type * as structs from "./structs";
export type { structs };
