// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

// This is a generated file. Do not edit manually.
// It has been generated by running `npx circom-contract-gen`
// on the circom-poseidon contract (https://github.com/0xPARC/circom-poseidon)

contract PoseidonT3 {
    function poseidon(uint256[2] memory input) public pure returns (uint256) {
        // ... (Poseidon hash implementation)
    }
}
