// scripts/deploy.js
const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");
const { poseidonContract } = require("circomlibjs");

// --- Inlined Poseidon Deployment Functions ---

async function _deployPoseidon(signer, inputs) {
    console.log(`🚀 开始部署 Poseidon (inputs: ${inputs}) 哈希合约...`);
    const poseidonBytecode = poseidonContract.createCode(inputs);
    const poseidonABI = poseidonContract.generateABI(inputs);
    const PoseidonFactory = new ethers.ContractFactory(poseidonABI, poseidonBytecode, signer);
    const poseidonHasher = await PoseidonFactory.deploy();
    await poseidonHasher.waitForDeployment();
    const contractAddress = await poseidonHasher.getAddress();
    
    console.log(`✅ PoseidonHasher (inputs: ${inputs}) 合约部署成功！`);
    console.log(`📍 合约地址: ${contractAddress}`);
    return { address: contractAddress, contract: poseidonHasher };
}

async function main() {
  const [deployer] = await ethers.getSigners();
  const deployerAddress = await deployer.getAddress();
  console.log("Deploying contracts with the account:", deployerAddress);

  const poseidonDeployment = await _deployPoseidon(deployer, 2);
  const poseidonHasherAddress = poseidonDeployment.address;

  const poseidon5Deployment = await _deployPoseidon(deployer, 5);
  const poseidonHasher5Address = poseidon5Deployment.address;

  const verifierFactory = await ethers.getContractFactory("Groth16Verifier", deployer);
  const verifier = await verifierFactory.deploy();
  await verifier.waitForDeployment();
  const verifierAddress = await verifier.getAddress();
  console.log("Verifier deployed to:", verifierAddress);

  const executorFactory = await ethers.getContractFactory("Executor", deployer);
  const executor = await executorFactory.deploy(deployerAddress);
  await executor.waitForDeployment();
  const executorAddress = await executor.getAddress();
  console.log("Executor deployed to:", executorAddress);

  const entryPointFactory = await ethers.getContractFactory("EntryPoint", deployer);
  const entryPoint = await entryPointFactory.deploy();
  await entryPoint.waitForDeployment();
  const entryPointAddress = await entryPoint.getAddress();
  console.log("EntryPoint deployed to:", entryPointAddress);

  const factoryFactory = await ethers.getContractFactory("SmartAccountFactory", deployer);
  const factory = await factoryFactory.deploy(entryPointAddress);
  await factory.waitForDeployment();
  const factoryAddress = await factory.getAddress();
  console.log("SmartAccountFactory deployed to:", factoryAddress);

  const paymasterFactory = await ethers.getContractFactory("Paymaster", deployer);
  const paymaster = await paymasterFactory.deploy(entryPointAddress, deployerAddress);
  await paymaster.waitForDeployment();
  const paymasterAddress = await paymaster.getAddress();
  console.log("Paymaster deployed to:", paymasterAddress);

  const privacyPoolFactory = await ethers.getContractFactory("PrivacyPool", deployer);
  const privacyPool = await privacyPoolFactory.deploy(
    verifierAddress,
    poseidonHasherAddress,
    poseidonHasher5Address,
    deployerAddress
  );
  await privacyPool.waitForDeployment();
  const privacyPoolAddress = await privacyPool.getAddress();
  console.log("PrivacyPool deployed to:", privacyPoolAddress);

  console.log("✅ All contracts deployed successfully!");

  const contractsConfig = {
    PRIVACY_POOL_ADDRESS: privacyPoolAddress,
    PAYMASTER_ADDRESS: paymasterAddress,
    SMART_ACCOUNT_FACTORY_ADDRESS: factoryAddress,
    EXECUTOR_ADDRESS: executorAddress,
    VERIFIER_ADDRESS: verifierAddress,
    ENTRYPOINT_ADDRESS: entryPointAddress,
    POSEIDON_HASHER_ADDRESS: poseidonHasherAddress,
    POSEIDON_HASHER5_ADDRESS: poseidonHasher5Address,
  };

  Object.entries(contractsConfig).forEach(([label, value]) => {
    if (!ethers.isAddress(value) || value === ethers.ZeroAddress) {
      throw new Error(`Invalid address generated for ${label}: ${value}`);
    }
  });

  const configPath = path.join(__dirname, "..", "frontend", "src", "config", "contracts.ts");
  const configContent = `// Generated by scripts/deploy.js\nexport const CONTRACTS = ${JSON.stringify(contractsConfig, null, 2)} as const;\n`;
  fs.writeFileSync(configPath, configContent);
  console.log(`✅ Frontend configuration written to ${configPath}`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
