// scripts/deploy.ts
import { ethers } from "hardhat";
import fs from "fs";
import path from "path";
import { deployPoseidon } from "./deploy-poseidon";
import { deployPoseidon5 } from "./deploy-poseidon5";

async function main() {
  const [deployer] = await ethers.getSigners();
  const deployerAddress = await deployer.getAddress();
  console.log("Deploying contracts with the account:", deployerAddress);

  const poseidonResult = await deployPoseidon(deployer);
  const poseidonHasherAddress = poseidonResult.address;
  console.log("✅ PoseidonHasher deployed to:", poseidonHasherAddress);

  const poseidon5Result = await deployPoseidon5(deployer);
  const poseidonHasher5Address = poseidon5Result.address;
  console.log("✅ PoseidonHasher5 deployed to:", poseidonHasher5Address);

  const verifierName = process.env.USE_MOCK_VERIFIER === "true" ? "MockVerifier" : "Verifier";
  console.log(`Deploying ${verifierName}...`);
  const verifierFactory = await ethers.getContractFactory(verifierName, deployer);
  const verifier = await verifierFactory.deploy();
  await verifier.waitForDeployment();
  const verifierAddress = await verifier.getAddress();
  console.log("Verifier deployed to:", verifierAddress);

  const executorFactory = await ethers.getContractFactory("Executor", deployer);
  const executor = await executorFactory.deploy(deployerAddress);
  await executor.waitForDeployment();
  const executorAddress = await executor.getAddress();
  console.log("Executor deployed to:", executorAddress);

  const entryPointFactory = await ethers.getContractFactory("EntryPoint", deployer);
  const entryPoint = await entryPointFactory.deploy();
  await entryPoint.waitForDeployment();
  const entryPointAddress = await entryPoint.getAddress();
  console.log("EntryPoint deployed to:", entryPointAddress);

  const factoryFactory = await ethers.getContractFactory("SmartAccountFactory", deployer);
  const factory = await factoryFactory.deploy(entryPointAddress);
  await factory.waitForDeployment();
  const factoryAddress = await factory.getAddress();
  console.log("SmartAccountFactory deployed to:", factoryAddress);

  const paymasterFactory = await ethers.getContractFactory("Paymaster", deployer);
  const paymaster = await paymasterFactory.deploy(entryPointAddress, deployerAddress);
  await paymaster.waitForDeployment();
  const paymasterAddress = await paymaster.getAddress();
  console.log("Paymaster deployed to:", paymasterAddress);

  console.log("\n🏊 Deploying PrivacyPool with official Poseidon hashers...");
  const privacyPoolFactory = await ethers.getContractFactory("PrivacyPool", deployer);
  const privacyPool = await privacyPoolFactory.deploy(
    verifierAddress,
    poseidonHasherAddress,
    poseidonHasher5Address,
    deployerAddress
  );
  await privacyPool.waitForDeployment();
  const privacyPoolAddress = await privacyPool.getAddress();
  console.log("✅ PrivacyPool deployed to:", privacyPoolAddress);

  const contractsConfig = {
    PRIVACY_POOL_ADDRESS: privacyPoolAddress,
    PAYMASTER_ADDRESS: paymasterAddress,
    SMART_ACCOUNT_FACTORY_ADDRESS: factoryAddress,
    EXECUTOR_ADDRESS: executorAddress,
    VERIFIER_ADDRESS: verifierAddress,
    ENTRYPOINT_ADDRESS: entryPointAddress,
    POSEIDON_HASHER_ADDRESS: poseidonHasherAddress,
    POSEIDON_HASHER5_ADDRESS: poseidonHasher5Address,
  } as const;

  Object.entries(contractsConfig).forEach(([label, value]) => {
    if (!ethers.isAddress(value) || value === ethers.ZeroAddress) {
      throw new Error(`Invalid address generated for ${label}: ${value}`);
    }
  });

  console.log("\nUpdating frontend configuration...");
  const configDir = path.join(__dirname, "..", "frontend", "src", "config");
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }
  const configPath = path.join(configDir, "contracts.ts");
  const configContent = `// This file is auto-generated by scripts/deploy.ts.
// Do not edit this file manually.

export const CONTRACTS = ${JSON.stringify(contractsConfig, null, 2)} as const;
`;

  fs.writeFileSync(configPath, configContent);
  console.log(`Frontend configuration updated at ${configPath}`);

  console.log("\n🎉 All contracts deployed successfully!");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
