// scripts/deploy.ts
import { ethers } from "hardhat";
import fs from "fs";
import path from "path";
import { deployPoseidon } from "./deploy-poseidon";
import { deployPoseidon5 } from "./deploy-poseidon5";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with the account:", deployer.address);

  // Deploy Poseidon Hasher first using the new official implementation
  console.log("\n🔧 Deploying official Poseidon hasher...");
  const poseidonResult = await deployPoseidon();
  const poseidonHasherAddress = poseidonResult.address;
  console.log("✅ Official PoseidonHasher deployed to:", poseidonHasherAddress);

  // Deploy Poseidon5 Hasher for public inputs hashing
  console.log("\n🔧 Deploying Poseidon5 hasher for public inputs...");
  const poseidon5Result = await deployPoseidon5();
  const poseidonHasher5Address = poseidon5Result.address;
  console.log("✅ PoseidonHasher5 deployed to:", poseidonHasher5Address);

  // Deploy Verifier
  const verifier = await ethers.deployContract("Verifier");
  await verifier.waitForDeployment();
  const verifierAddress = await verifier.getAddress();
  console.log("Verifier deployed to:", verifierAddress);

  // Deploy Executor
  const executor = await ethers.deployContract("Executor", [deployer.address]);
  await executor.waitForDeployment();
  const executorAddress = await executor.getAddress();
  console.log("Executor deployed to:", executorAddress);

  // Deploy SmartAccountFactory
  const entryPoint = await ethers.deployContract("EntryPoint");
  await entryPoint.waitForDeployment();
  const entryPointAddress = await entryPoint.getAddress();
  const factory = await ethers.deployContract("SmartAccountFactory", [
    entryPointAddress,
  ]);
  await factory.waitForDeployment();
  const factoryAddress = await factory.getAddress();
  console.log("SmartAccountFactory deployed to:", factoryAddress);

  // Deploy Paymaster
  const paymaster = await ethers.deployContract("Paymaster", [
    entryPointAddress,
    deployer.address,
  ]);
  await paymaster.waitForDeployment();
  const paymasterAddress = await paymaster.getAddress();
  console.log("Paymaster deployed to:", paymasterAddress);

  // Deploy PrivacyPool with the official Poseidon hasher
  console.log("\n🏊 Deploying PrivacyPool with official Poseidon hasher...");
  const privacyPool = await ethers.deployContract("PrivacyPool", [
    verifierAddress,
    poseidonHasherAddress,
    poseidonHasher5Address,
    deployer.address,
  ]);
  await privacyPool.waitForDeployment();
  const privacyPoolAddress = await privacyPool.getAddress();
  console.log("✅ PrivacyPool deployed to:", privacyPoolAddress);

  // --- Automatic Frontend Configuration ---
  console.log("\nUpdating frontend configuration...");
  const configDir = path.join(__dirname, "..", "frontend", "src", "config");
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir);
  }
  const configPath = path.join(configDir, "contracts.ts");
  const configContent = `// This file is auto-generated by the deployment script.
// Do not edit this file manually.

export const CONTRACTS = {
  PRIVACY_POOL_ADDRESS: "${privacyPoolAddress}",
  PAYMASTER_ADDRESS: "${paymasterAddress}",
  SMART_ACCOUNT_FACTORY_ADDRESS: "${factoryAddress}",
  EXECUTOR_ADDRESS: "${executorAddress}",
  VERIFIER_ADDRESS: "${verifierAddress}",
  ENTRYPOINT_ADDRESS: "${entryPointAddress}",
  POSEIDON_HASHER_ADDRESS: "${poseidonHasherAddress}",
  POSEIDON_HASHER5_ADDRESS: "${poseidonHasher5Address}",
} as const;
`;

  fs.writeFileSync(configPath, configContent);
  console.log(`Frontend configuration updated at ${configPath}`);
  
  console.log("\n🎉 All contracts deployed successfully with official Poseidon hasher!");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });